image: "rust:latest"

stages:
  - test

redox-pkg-test:
  stage: test
  script:
    - cargo test -p redox-pkg --features indicatif
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
